// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const Access = {
    Public: "public",
    Private: "private",
} as const;

export type Access = (typeof Access)[keyof typeof Access];
